# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Outrunner < Formula
  desc "Ephemeral GitHub Actions runners, no Kubernetes required"
  homepage "https://github.com/Rubio-Enterprises/gha-outrunner"
  version "1.2.0-strubio.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/Rubio-Enterprises/gha-outrunner/releases/download/v1.2.0-strubio.1/outrunner_1.2.0-strubio.1_darwin_arm64.tar.gz"
      sha256 "d0790344f4e408824ae89a4c6746dd156b87f22917a842723a8abae2188dae2d"

      define_method(:install) do
        bin.install "outrunner"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rubio-Enterprises/gha-outrunner/releases/download/v1.2.0-strubio.1/outrunner_1.2.0-strubio.1_linux_amd64.tar.gz"
      sha256 "23989efbdeadb2c6d67d24f4b38e3f5939318dc48087ffdf6583914629b00815"
      define_method(:install) do
        bin.install "outrunner"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Rubio-Enterprises/gha-outrunner/releases/download/v1.2.0-strubio.1/outrunner_1.2.0-strubio.1_linux_arm64.tar.gz"
      sha256 "e07af8cd85aefa375f926e72eb1a1707e549be2bf19fcbaa62afe5eaf4cb4696"
      define_method(:install) do
        bin.install "outrunner"
      end
    end
  end

  test do
    system "#{bin}/outrunner", "--version"
  end
end
