name: Lint

on:
  push:
    branches: [main]
  pull_request:

jobs:
  lint:
    runs-on: ${{ fromJSON(vars.RUNNER_MACOS || '["macos-latest"]') }}
    steps:
      - name: Checkout
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4

      - name: Set up Homebrew
        uses: Homebrew/actions/setup-homebrew@d3565f64e59130f1fd713440276f7d3e11079b88 # main
        with:
          token: ${{ github.token }}

      - name: Audit formulas
        run: brew audit --formula --tap rubio-enterprises/tap

      - name: Audit casks
        run: brew audit --cask --tap rubio-enterprises/tap

      - name: Style check
        run: brew style rubio-enterprises/tap

      - name: Livecheck (casks)
        run: brew livecheck --cask --tap rubio-enterprises/tap
